# Defaults for all MNSC datasets
extends: ["../base.yaml#"]
dataset_path: AudioLLMs/Multitask-National-Speech-Corpus-v1-extend
language: en
split: train
accented: true
audio_column: context
target_column: answer
instruction_column: instruction
