task_name: voxangeles_phoneme_counting
dataset_path: DynamicSuperb/PhoneSegmentCounting_VoxAngeles
modality: audio
language: en
split: test
preprocessor: GeneralPreprocessor
postprocessor: GeneralPostprocessor
audio_column: audio
target_column: label
instruction_column: instruction
user_prompt: "You are an expert at counting phones in the context of phonemes, and always attempt to answer. You will be given an audio sample, listen carefully."
long_audio_processing_logic: truncate

generation_kwargs:
  temperature: 0.0001
  max_completion_tokens: 64

metrics:
  - metric: llm_judge_binary
  - metric: detailed_judge_prompt
