task_name: voxangeles_phoneme_classification
dataset_path: DynamicSuperb/PhonologicalFeatureClassification_VoxAngeles-Phone
modality: audio
language: en
split: test
preprocessor: GeneralPreprocessor
postprocessor: GeneralPostprocessor
audio_column: audio
target_column: label
instruction_column: instruction
user_prompt: "You are an audio model that is an expert at identifying phonemes. Listen to the given audio clip. Based on the following instructions, answer the question. Always attempt to answer."
long_audio_processing_logic: truncate

generation_kwargs:
  temperature: 0.0001
  max_completion_tokens: 64

metrics:
  - metric: llm_judge_binary
  - metric: detailed_judge_prompt
